### ISSUE TITLE
RabbitMQ transport should disable unused timeout manager queues

### ISSUE THREAD

**Issue by bording** [Particular/ServiceControl.Monitoring#105]
When using the RabbitMQ transport with Monitoring, it should call the `DisableTimeoutManager` API to turn off the unused timeout manager queues:

https://docs.particular.net/transports/rabbitmq/delayed-delivery#backwards-compatibility-disabling-the-timeout-manager

**Comment by mikeminutillo** [comment]
The Monitoring instance does not know which transport is being used until runtime. In order to resolve this issue we'd need a [custom version of the rabbit transport](https://github.com/Particular/ServiceControl.Monitoring/tree/develop/src/ServiceControl.Transports.RabbitMQ) that calls this API when it is selected.

**Comment by bording** [comment]
Another thing to consider would be to move up to NSB 7 here as well. The 5.x RabbitMQ transport disables the timeout manager by default.

**Comment by tmasternak** [comment]
@bording can we close this one as https://github.com/Particular/ServiceControl.Monitoring/pull/143 is merged?

**Comment by bording** [comment]
Yes, moving to NSB 7 fixes this!
