### ISSUE TITLE
When running only -s (setup command) the installers are not run

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServiceControl.Monitoring#17]
When running -s command the result is that [`Endpoint.Create`](https://github.com/Particular/ServiceControl.Monitoring/blob/develop/src/ServiceControl.Monitoring/Hosting/Commands/SetupCommand.cs#L12) is called which does not run installers. We probably need to call `Endpoint.Start` to make that happen.

**Comment by mikeminutillo** [comment]
I feel like this is a flaw with core. It should be possible to run the installers without spinning up a receiver and potentially trying to handle messages. I guess it's a breaking change to try and fix that.

@Particular/nservicebus-maintainers thoughts?

**Comment by andreasohlund** [comment]
I agree that this is a flaw, we've been fighting this since day one. Eg. the host have to do a partial setup/start to be able to run the installers properly 

https://github.com/Particular/NServiceBus.Host/blob/develop/src/NServiceBus.Hosting.Windows/GenericHost.cs#L71

That said, my personal stance is that we should remove our installation support completely and instead pursue the new script generation approach that sqlpersistence and the perf counters are doing. This way we eliminate the need to run the users config code (yes this creates other problems like how to determine script variables like queue names, what satellites are enabled etc at build time)

cc @SimonCropp

**Comment by mikeminutillo** [comment]
>  Endpoint.Create is called which does not run installers. We probably need to call Endpoint.Start to make that happen.

The installers are run as a part of [Endpoint Initialization](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/InitializableEndpoint.cs#L68) which is called as a part of [`Endpoint.Create`](https://github.com/Particular/NServiceBus/blob/develop/src/NServiceBus.Core/Endpoint.cs#L18).

**Comment by mikeminutillo** [comment]
Tested with @tmasternak 

`Endpoint.Create` does run the installers.
