### ISSUE TITLE
Passthrough data to the service caller

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl.Monitoring#2]
With https://github.com/Particular/NServiceBus.Metrics/pull/17 it is possible to consume the data created with the metrics component without needing to reference metrics.net. Essentially you can have either a handler or an early pipeline behavior which takes the raw json and adds it to a ring buffer. Whenever a client calls on the web API the ring buffer will be fed back to the caller. Piping the json schema to the client. 

This might simplify the work on #1 

Thoughts @SzymonPobiega @Scooletz @seanfarmar @weralabaj?

**Comment by SzymonPobiega** [comment]
@danielmarbach I think we can't do it for two reasons:
 * We have derived metrics in the scope of the TF. Derived metrics are based on raw metrics sent from the endpoints. We need to parse and understand the data in order to implement them
 * I expect that the SP UI will need the metrics in various groupings other than "per endpoint" e.g. give us all "Processing time" metrics for all endpoints. In order to do this we need to slice and dice the metrics in the backend component.
