### ISSUE TITLE
Unable to provide schema name for queue creation (SQL Transport)

### ISSUE THREAD

**Issue by Tobias-Gr** [Particular/ServiceControl.Monitoring#94]
ServiceControl accepts a connection string like this and respects the schema name:

Server=localhost;Initial Catalog=foo;Integrated Security=true; Queue Schema=Queues

But using this string in ServiceControl.Monitoring results in an error:

Could not add new instance because of the following errors: ServiceControl.Monitoring.exe threw an error when creating queues. [...] Keyword not supported: 'Queue schema'

**Comment by tmasternak** [comment]
@Tobias-Gr ServiceControl.Monitoring is running with v3 of Sql transport and that's why it does not accept `Queue schema` part. Instead it expect the schema to be used in the [address](https://docs.particular.net/transports/sql/addressing#format).

To change the Sc.Monitoring name and at the same time it's input queue you need to change the configuration file manually and trigger the the queue setup. The steps are covered [here](https://docs.particular.net/servicecontrol/monitoring-instances/installation/creating-config-file#host-settings-monitoringendpointname).

That being said I've tried it myself to make sure all works fine and it looks that currently the custom name cannot contain `@` symbol which prevents the custom sql schema usage. I'm tagging this as bug.

I'll update you as soon as we have the fix.

**Comment by tmasternak** [comment]
@Tobias-Gr I've just released ServiceControl 1.45.1. It ships with updated version of monitoring instance which supports `Queue schema` in the SqlServer connection string.
